import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id 'java'
    id("org.jetbrains.intellij.platform") version "2.11.0"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // Adjust Java version as needed
    }
}

group = 'intellij.jasper.report'
// version is defined in gradle.properties

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea ideaVersion

        // bundledPlugin 'com.intellij.java'

        pluginVerifier()
        zipSigner()
        instrumentationTools()

        testFramework TestFrameworkType.Platform.INSTANCE
    }

    testImplementation 'junit:junit:4.13.2'
    // other dependencies, e.g., 3rd-party libraries
}

intellijPlatform {
    pluginVerification {
        ides {
            recommended()
        }
    }
}


patchPluginXml {
    sinceBuild = "253"
    untilBuild = provider { null }
}
